version: '3.3'
services:
  pgsql:
    image: 'postgres:14-alpine'
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRESS_DB: '${DB_DATABASE}'
      POSTGRESS_USER: 's{DB_USERNAME}'
      POSTGRESS_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
    networks:
      - phpnetwork
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s

  laravel:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - phpnetwork
    depends_on:
      - pgsql

  artisan:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    user: laravel
    networks:
      - phpnetwork
    depends_on:
      - laravel
    entrypoint: ['php', '/var/www/html/artisan']

  composer:
    build:
      context: ./php/composer
      dockerfile: Dockerfile
    container_name: composer
    volumes:
        - ./app:/var/www/html
    working_dir: /var/www/html
    user: laravel
    networks:
        - phpnetwork
    depends_on:
        - laravel
    entrypoint: ['composer', '--ignore-platform-reqs']

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./app:/var/www/html:delegated
      - nginxlogs:/var/log/nginx
    depends_on:
      - pgsql
      - laravel

networks:
  phpnetwork:
    driver: bridge

volumes:
  dbdata:
    driver: local
  nginxlogs:
    driver: local